name: Build BetterCombat Jar

on:
  workflow_dispatch:
  push:
    branches: ["1.20.1"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/upload-artifact@v4

    - name: Set up JDK 17
      uses: actions/upload-artifact@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission to Gradle wrapper
      run: chmod +x ./gradlew

    - name: Build mod
      run: ./gradlew build

    - name: Upload built jar
      uses: actions/upload-artifact@v4
      with:
        name: BetterCombat-Jar
        path: build/libs/*.jar
